insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (1, 'Eric', 'Maunggora', 1, 60.04);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (2, 'Daniel', 'Chyzne', 2, 40.19);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (3, 'Doris', 'Xidoupu', 3, 37.83);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (4, 'Janice', 'Jõhvi', 4, 60.81);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (5, 'Emily', 'Taimaman', 5, 6.69);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (6, 'Annie', 'Yongledian', 6, 81.21);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (7, 'Marie', 'Lukunor', 7, 68.67);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (8, 'Nicholas', 'Kiarajangkung', 8, 40.97);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (9, 'Kevin', 'Krasnoshchekovo', 9, 89.93);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (10, 'Stephanie', 'Jing’an', 10, 17.58);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (11, 'Kenneth', 'Dar an Nasr', 11, 22.07);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (12, 'Kimberly', 'Opi', 12, 92.49);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (13, 'Ernest', 'Milwaukee', 13, 67.82);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (14, 'Adam', 'Maninihon', 14, 72.03);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (15, 'Joan', 'Banes', 15, 84.23);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (16, 'Bruce', 'Merkezköy', 16, 47.63);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (17, 'Juan', 'Mir', 17, 58.78);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (18, 'Margaret', 'Sankt Andrä-Höch', 18, 71.76);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (19, 'Raymond', 'Meijiang', 19, 84.02);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (20, 'Louis', 'Nordeste', 20, 34.77);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (21, 'Andrea', 'Imsida', 21, 23.96);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (22, 'Kimberly', 'Kramsk', 22, 14.53);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (23, 'Victor', 'La Loma', 23, 24.07);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (24, 'Victor', 'Tengah', 24, 72.19);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (25, 'Jeffrey', 'La Caya', 25, 11.06);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (26, 'Stephen', 'Umeå', 26, 11.49);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (27, 'Lori', 'Novorozhdestvenskaya', 27, 21.49);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (28, 'Ann', 'Xiaxi', 28, 90.04);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (29, 'Jennifer', 'Yanacancha', 29, 73.45);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (30, 'Donna', 'Tandalti', 30, 18.9);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (31, 'Clarence', 'Silveiros', 31, 88.81);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (32, 'Lois', 'Salmi', 32, 83.59);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (33, 'Fred', 'Trablice', 33, 40.55);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (34, 'Philip', 'Concord', 34, 60.89);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (35, 'Patricia', 'Dhrosiá', 35, 67.26);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (36, 'Gloria', 'Chum Phae', 36, 80.99);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (37, 'Earl', 'Mekarsari', 37, 33.26);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (38, 'Virginia', 'Malinta', 38, 35.79);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (39, 'Samuel', 'Jongiyeh', 39, 74.68);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (40, 'Judy', 'Isu', 40, 51.16);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (41, 'Jason', 'Perdões', 41, 56.14);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (42, 'Maria', 'Basse-Terre', 42, 20.95);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (43, 'Matthew', 'Seattle', 43, 49.28);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (44, 'Nicholas', 'Hola Prystan’', 44, 77.57);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (45, 'Chris', 'Tessaoua', 45, 10.06);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (46, 'Cheryl', 'Qiulu', 46, 78.25);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (47, 'Anthony', 'Changleng', 47, 20.27);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (48, 'Norma', 'Guantang', 48, 87.07);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (49, 'Stephanie', 'Huntsville', 49, 35.6);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (50, 'Kimberly', 'Shuangjie', 50, 23.3);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (51, 'Diane', 'Xanxerê', 51, 46.31);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (52, 'Jose', 'Réo', 52, 42.04);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (53, 'Judy', 'Rossosh’', 53, 66.51);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (54, 'Shirley', 'Kayasula', 54, 30.63);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (55, 'Mildred', 'Bor', 55, 50.99);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (56, 'Philip', 'Nanterre', 56, 2.51);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (57, 'Eugene', 'Paris 02', 57, 73.91);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (58, 'Bobby', 'Basseterre', 58, 13.7);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (59, 'Victor', 'Keleng', 59, 79.12);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (60, 'Denise', 'Araraquara', 60, 15.52);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (61, 'Phyllis', 'Baucau', 61, 43.07);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (62, 'Craig', 'Colares', 62, 5.26);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (63, 'Bruce', 'Ash Shaykh ‘Uthman', 63, 86.26);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (64, 'Janet', 'Xinfeng', 64, 79.36);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (65, 'Nicole', 'Popovice', 65, 85.24);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (66, 'Nicole', 'Suci Kaler', 66, 98.92);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (67, 'Cynthia', 'Catalão', 67, 55.26);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (68, 'Jeffrey', 'Al Buq‘ah', 68, 11.4);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (69, 'Sean', 'West Palm Beach', 69, 58.04);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (70, 'Michael', 'Guaratinguetá', 70, 79.5);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (71, 'Kimberly', 'Luleå', 71, 41.84);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (72, 'Anthony', 'Göteborg', 72, 36.93);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (73, 'Mildred', 'Saint-Tite', 73, 79.58);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (74, 'Lillian', 'Maceda', 74, 39.0);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (75, 'Laura', 'Bozkow', 75, 70.21);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (76, 'Sandra', 'Piquete', 76, 18.81);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (77, 'Jason', 'Nacka', 77, 1.86);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (78, 'Jose', 'Sokobanteng', 78, 38.6);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (79, 'Jessica', 'Borik', 79, 22.68);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (80, 'Rachel', 'Miratejo', 80, 75.16);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (81, 'Marie', 'Las Vegas', 81, 56.45);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (82, 'Karen', 'Paris 15', 82, 56.02);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (83, 'Philip', 'Dolgoprudnyy', 83, 57.5);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (84, 'Donald', 'Stockholm', 84, 89.3);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (85, 'Jason', 'Jawa', 85, 39.68);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (86, 'Amanda', 'Beixiaoying', 86, 34.85);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (87, 'Billy', 'Songshu', 87, 30.49);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (88, 'Louis', 'Mayo', 88, 20.37);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (89, 'Patricia', 'Bruxelles', 89, 54.38);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (90, 'Catherine', 'Magutian', 90, 38.22);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (91, 'Scott', 'Zwolle', 91, 24.67);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (92, 'Craig', 'Shenshu', 92, 90.94);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (93, 'Gloria', 'Hisya', 93, 12.07);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (94, 'Steve', 'Mama', 94, 70.88);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (95, 'Russell', 'Klang', 95, 59.85);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (96, 'Albert', 'Azua', 96, 88.29);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (97, 'John', 'Pytalovo', 97, 40.32);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (98, 'Larry', 'Nantes', 98, 30.31);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (99, 'Janice', 'Kamubheka', 99, 3.73);
insert into ACTIVITIESTYPES  (ID, NAME, OBSERVATIONS, OPTLOCK, ORDEN) values (100, 'James', 'Midland', 100, 93.31);